# Generated by Django 5.1.15 on 2026-07-11 00:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('scope', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='planned', max_length=20)),
                ('auditor_ids', models.JSONField(blank=True, default=list)),
                ('checklist_items', models.JSONField(blank=True, default=list)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('report_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audits',
                'db_table': 'audits',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='NonConformity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='open', max_length=20)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('closing_notes', models.TextField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_conformities', to='quality_safety.audit')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ncrs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Non-Conformity',
                'verbose_name_plural': 'Non-Conformities',
                'db_table': 'non_conformities',
            },
        ),
        migrations.CreateModel(
            name='CAPA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(help_text='corrective or preventive', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='open', max_length=20)),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('closing_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('non_conformity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capas', to='quality_safety.nonconformity')),
            ],
            options={
                'verbose_name': 'CAPA',
                'verbose_name_plural': 'CAPAs',
                'db_table': 'capas',
            },
        ),
        migrations.CreateModel(
            name='QualityDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(blank=True, max_length=20, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_revision', 'In Revision'), ('approved', 'Approved'), ('archived', 'Archived'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('version_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_qdocs', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_qdocs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quality Document',
                'verbose_name_plural': 'Quality Documents',
                'db_table': 'quality_documents',
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hazard', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('probability', models.IntegerField(help_text='1-5 scale')),
                ('severity', models.IntegerField(help_text='1-5 scale')),
                ('risk_level', models.IntegerField(default=1, editable=False)),
                ('mitigation_measures', models.TextField(blank=True, null=True)),
                ('reeval_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_assessments',
                'ordering': ['-risk_level'],
            },
        ),
        migrations.CreateModel(
            name='SafetyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('confidential', models.BooleanField(default=False)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('analysis', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='reported', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_safety_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safety_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
