# Generated by Django 5.1.15 on 2026-07-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_safety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capa',
            name='capa_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nonconformity',
            name='ncr_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='type',
            field=models.CharField(choices=[('internal', 'Internal'), ('regulatory', 'Regulatory'), ('supplier', 'Supplier'), ('pedagogical', 'Pedagogical'), ('safety', 'Safety')], max_length=30),
        ),
    ]
