# Generated by Django 5.1.15 on 2026-07-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_safety', '0002_add_numbers_and_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyevent',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Under Investigation'), ('analyzed', 'Analyzed'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=20),
        ),
    ]
