# Generated by Django 6.0.7 on 2026-08-08 20:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file_key', models.CharField(max_length=500, unique=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Landing Media',
                'verbose_name_plural': 'Landing Media',
                'db_table': 'landing_media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_version', models.IntegerField(default=0)),
                ('published_content', models.JSONField(blank=True, default=dict, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Landing Section',
                'verbose_name_plural': 'Landing Sections',
                'db_table': 'landing_sections',
                'ordering': ['sort_order', 'key'],
            },
        ),
    ]
