# Generated by Django 5.1.15 on 2026-08-09 00:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='landingsection',
            name='theme',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='LandingSectionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('content', models.JSONField(blank=True, default=list)),
                ('theme', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_section_versions', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='landing.landingsection')),
            ],
            options={
                'verbose_name': 'Landing Section Version',
                'verbose_name_plural': 'Landing Section Versions',
                'db_table': 'landing_section_versions',
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('section', 'version'), name='uniq_landing_section_version')],
            },
        ),
    ]
