# Generated by Django 5.1.15 on 2026-07-11 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration', models.CharField(max_length=20, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True)),
                ('base_location', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='available', max_length=20)),
                ('airframe_hours', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('engine_hours', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('propeller_hours', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('last_maintenance', models.DateTimeField(blank=True, null=True)),
                ('next_maintenance', models.DateTimeField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('certification_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircraft',
                'db_table': 'aircraft',
                'ordering': ['registration'],
            },
        ),
        migrations.CreateModel(
            name='FlightLessonTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('objective', models.TextField(blank=True, null=True)),
                ('competencies', models.JSONField(blank=True, default=list)),
                ('planned_duration', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('briefing_time', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('flight_time', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('debriefing_time', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('success_criteria', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flight_lesson_templates',
                'ordering': ['program', 'lesson_number'],
            },
        ),
        migrations.CreateModel(
            name='FlightProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('program', models.CharField(choices=[('PPL', 'Private Pilot License'), ('CPL', 'Commercial Pilot License'), ('IR', 'Instrument Rating'), ('MEP', 'Multi-Engine Piston'), ('MCC', 'Multi-Crew Cooperation')], max_length=10)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'Flight Program',
                'verbose_name_plural': 'Flight Programs',
                'db_table': 'flight_programs',
            },
        ),
        migrations.CreateModel(
            name='FlightLesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('flight_duration', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('briefing_duration', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('debrief_duration', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('exercises_completed', models.JSONField(blank=True, default=list)),
                ('competencies_acquired', models.JSONField(blank=True, default=list)),
                ('difficulties', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('pedagogical_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_lessons', to='flight_training.aircraft')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_lessons', to='students.flightinstructor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_lessons', to='students.student')),
                ('lesson_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flight_training.flightlessontemplate')),
            ],
            options={
                'verbose_name': 'Flight Lesson',
                'verbose_name_plural': 'Flight Lessons',
                'db_table': 'flight_lessons',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='FlightPreparation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weather_check', models.BooleanField(default=False)),
                ('notam_check', models.BooleanField(default=False)),
                ('performance_check', models.BooleanField(default=False)),
                ('document_check', models.BooleanField(default=False)),
                ('medical_check', models.BooleanField(default=False)),
                ('lesson_objectives', models.TextField(blank=True, null=True)),
                ('briefing_notes', models.TextField(blank=True, null=True)),
                ('prepared_at', models.DateTimeField(auto_now_add=True)),
                ('flight_lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preparation', to='flight_training.flightlesson')),
            ],
            options={
                'verbose_name': 'Flight Preparation',
                'verbose_name_plural': 'Flight Preparations',
                'db_table': 'flight_preparations',
            },
        ),
        migrations.AddField(
            model_name='flightlessontemplate',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_templates', to='flight_training.flightprogram'),
        ),
        migrations.CreateModel(
            name='InstructorAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(help_text='0=Monday, 6=Sunday')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='students.flightinstructor')),
            ],
            options={
                'verbose_name': 'Instructor Availability',
                'verbose_name_plural': 'Instructor Availabilities',
                'db_table': 'instructor_availability',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='flight_training.aircraft')),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'verbose_name_plural': 'Maintenance Records',
                'db_table': 'maintenance_records',
            },
        ),
        migrations.CreateModel(
            name='ResourceBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=30)),
                ('resource_id', models.UUIDField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('activity_type', models.CharField(blank=True, max_length=30, null=True)),
                ('activity_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(default='confirmed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resource_bookings',
            },
        ),
        migrations.AddIndex(
            model_name='flightlesson',
            index=models.Index(fields=['student', 'scheduled_date'], name='flight_less_student_fa135b_idx'),
        ),
        migrations.AddIndex(
            model_name='flightlesson',
            index=models.Index(fields=['instructor', 'scheduled_date'], name='flight_less_instruc_fdf67f_idx'),
        ),
        migrations.AddIndex(
            model_name='flightlesson',
            index=models.Index(fields=['status'], name='flight_less_status_4417a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flightlessontemplate',
            unique_together={('program', 'lesson_number')},
        ),
        migrations.AddIndex(
            model_name='resourcebooking',
            index=models.Index(fields=['resource_type', 'resource_id'], name='resource_bo_resourc_bb9ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcebooking',
            index=models.Index(fields=['start_time', 'end_time'], name='resource_bo_start_t_3d220d_idx'),
        ),
    ]
