# Generated by Django 6.0.7 on 2026-08-06 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_training', '0008_log_entry_grade'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='flightlogentry',
            new_name='flight_log__student_29e57b_idx',
            old_name='flight_log__student_7ccefb_idx',
        ),
        migrations.RenameIndex(
            model_name='flightlogentry',
            new_name='flight_log__status_4ea6a5_idx',
            old_name='flight_log__status_8b1c7d_idx',
        ),
        migrations.AddField(
            model_name='flightlesson',
            name='solo_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flightexercise',
            name='program',
            field=models.CharField(blank=True, choices=[('PPL', 'Private Pilot License'), ('CPL', 'Commercial Pilot License'), ('IR', 'Instrument Rating'), ('MEP', 'Multi-Engine Piston'), ('MCC', 'Multi-Crew Cooperation')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flightlesson',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
