# Generated by Django 6.0.7 on 2026-08-03 01:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('muted_types', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error'), ('broadcast', 'Broadcast'), ('announcement', 'Announcement'), ('reminder', 'Reminder'), ('flight_scheduled', 'Flight Scheduled'), ('flight_evaluated', 'Flight Evaluated'), ('solo_authorized', 'Solo Authorized'), ('course_scheduled', 'Course Scheduled'), ('exam_published', 'Exam Published'), ('exam_result', 'Exam Result'), ('quiz_result', 'Quiz Result'), ('module_published', 'Module Published'), ('enrollment', 'Enrollment'), ('progress_check', 'Progress Check'), ('skill_test', 'Skill Test'), ('certificate_issued', 'Certificate Issued'), ('document_expiring', 'Document Expiring'), ('application', 'Application'), ('contact_form', 'Contact Form'), ('invoice_created', 'Invoice Created'), ('invoice_overdue', 'Invoice Overdue'), ('payment_received', 'Payment Received'), ('contract_signed', 'Contract Signed'), ('ncr_opened', 'NCR Opened'), ('ncr_closed', 'NCR Closed'), ('audit_planned', 'Audit Planned'), ('audit_completed', 'Audit Completed'), ('capa_assigned', 'CAPA Assigned'), ('capa_due', 'CAPA Due'), ('safety_event', 'Safety Event'), ('quality_doc_approved', 'Quality Document Approved'), ('deadline', 'Deadline'), ('task_assigned', 'Task Assigned')], default='info', max_length=40),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL),
        ),
    ]
