# Generated by Django 6.0.7 on 2026-08-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_seed_library_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('submitted', 'Submitted'), ('withdrawn', 'Withdrawn')], default='pending', max_length=30),
        ),
    ]
