# Generated by Django 5.1.15 on 2026-07-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_training', '0003_add_ground_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
    ]
