# Generated by Django 5.1.15 on 2026-07-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_training', '0005_add_video_to_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='bibliography',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subject',
            name='prerequisites',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subject',
            name='required_documents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
