# Generated by Django 6.0.7 on 2026-08-01 23:22

import django.db.models.deletion
from django.db import migrations, models


def backfill_course_promotions(apps, schema_editor):
    Promotion = apps.get_model('students', 'Promotion')
    Course = apps.get_model('ground_training', 'Course')
    AcademicYear = apps.get_model('core', 'AcademicYear')

    for c in Course.objects.select_related('subject').all():
        ay = None
        if c.academic_year_id:
            ay = AcademicYear.objects.filter(id=c.academic_year_id).first()
        year = ay.start_date.year if ay else None
        program = c.subject.program if c.subject_id else None
        promo = None
        if program:
            if year:
                promo = Promotion.objects.filter(program=program, start_date__year=year).order_by('-start_date').first()
            if not promo:
                promo = Promotion.objects.filter(program=program, status='in_progress').order_by('-start_date').first()
            if not promo:
                promo = Promotion.objects.filter(program=program).order_by('-start_date').first()
        if promo:
            c.promotion_id = promo.id
            c.save(update_fields=['promotion'])


class Migration(migrations.Migration):

    dependencies = [
        ('ground_training', '0007_timeentry'),
        ('students', '0004_remove_student_academic_year_promotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.promotion'),
        ),
        migrations.RunPython(backfill_course_promotions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='course',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='academic_year',
        ),
    ]
