# Generated by Django 6.0.7 on 2026-08-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground_training', '0008_remove_course_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulelesson',
            name='video_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
