# Generated by Django 5.1.15 on 2026-07-11 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ground_training', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.CharField(blank=True, choices=[('PPL', 'Private Pilot License'), ('CPL', 'Commercial Pilot License'), ('IR', 'Instrument Rating'), ('MEP', 'Multi-Engine Piston'), ('MCC', 'Multi-Crew Cooperation')], max_length=10, null=True)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='issued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.student')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'db_table': 'certificates',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.CharField(blank=True, choices=[('PPL', 'Private Pilot License'), ('CPL', 'Commercial Pilot License'), ('IR', 'Instrument Rating'), ('MEP', 'Multi-Engine Piston'), ('MCC', 'Multi-Crew Cooperation')], max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('question_count', models.IntegerField(blank=True, null=True)),
                ('passing_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_attempts', models.IntegerField(default=3)),
                ('open_date', models.DateTimeField(blank=True, null=True)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ground_training.subject')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'exams',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PracticalEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_type', models.CharField(blank=True, max_length=20, null=True)),
                ('lesson_id', models.UUIDField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('competencies', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('improvements', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_evaluations', to='students.flightinstructor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_evaluations', to='students.student')),
            ],
            options={
                'db_table': 'practical_evaluations',
            },
        ),
        migrations.CreateModel(
            name='ProgressCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('lessons_to_repeat', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_checks', to='students.flightinstructor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_checks', to='students.student')),
            ],
            options={
                'db_table': 'progress_checks',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=30)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.TextField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ground_training.subject')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Question Bank',
                'db_table': 'question_bank',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('passing_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_attempts', models.IntegerField(default=1)),
                ('is_open', models.BooleanField(default=False)),
                ('open_date', models.DateTimeField(blank=True, null=True)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='ground_training.module')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'db_table': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='students.student')),
            ],
            options={
                'db_table': 'quiz_attempts',
            },
        ),
        migrations.CreateModel(
            name='SkillTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('report_url', models.CharField(blank=True, max_length=500, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='authorized', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_skill_tests', to='students.flightinstructor')),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_tests_examined', to='students.flightinstructor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_tests', to='students.student')),
            ],
            options={
                'db_table': 'skill_tests',
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt', models.IntegerField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('is_passed', models.BooleanField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='students.student')),
            ],
            options={
                'db_table': 'exam_attempts',
                'unique_together': {('exam', 'student', 'attempt')},
            },
        ),
        migrations.CreateModel(
            name='StudentCompetency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('program', models.CharField(blank=True, choices=[('PPL', 'Private Pilot License'), ('CPL', 'Commercial Pilot License'), ('IR', 'Instrument Rating'), ('MEP', 'Multi-Engine Piston'), ('MCC', 'Multi-Crew Cooperation')], max_length=10, null=True)),
                ('competency', models.CharField(max_length=255)),
                ('status', models.CharField(default='not_started', max_length=30)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Competency',
                'verbose_name_plural': 'Student Competencies',
                'db_table': 'student_competencies',
                'unique_together': {('student', 'program', 'competency')},
            },
        ),
    ]
