# Generated by Django 5.1.15 on 2026-07-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_add_i18n_fields'),
        ('ground_training', '0003_add_ground_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ground_training.module'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='program',
            field=models.CharField(blank=True, choices=[('PPL', 'Private Pilot License'), ('CPL', 'Commercial Pilot License'), ('IR', 'Instrument Rating'), ('MEP', 'Multi-Engine Piston'), ('MCC', 'Multi-Crew Cooperation')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('progress_test', 'Progress Test'), ('module_exam', 'Module Exam'), ('mock_exam', 'Mock Exam'), ('final_exam', 'Final Internal Exam')], default='quiz', max_length=30),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('matching', 'Matching'), ('ordering', 'Ordering'), ('case_study', 'Case Study')], default='mcq', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentcompetency',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('acquired', 'Acquired'), ('needs_reinforcement', 'Needs Reinforcement')], default='not_started', max_length=30),
        ),
    ]
