# Generated by Django 6.0.7 on 2026-07-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='report_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
