# Generated by Django 6.0.7 on 2026-08-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_final_exam_manual_grading'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='finalexamquestion',
            new_name='final_exam__subject_9b1604_idx',
            old_name='final_q_subject_mod',
        ),
        migrations.RenameIndex(
            model_name='finalexamquestion',
            new_name='final_exam__difficu_585126_idx',
            old_name='final_q_difficulty',
        ),
        migrations.RenameIndex(
            model_name='finalexamquestion',
            new_name='final_exam__questio_46f222_idx',
            old_name='final_q_type',
        ),
        migrations.AddField(
            model_name='examattempt',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='violations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
