# Generated by Django 6.0.7 on 2026-07-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director_general', 'Director General'), ('head_of_training', 'Head of Training'), ('chief_ground_instructor', 'Chief Ground Instructor'), ('ground_instructor', 'Ground Instructor'), ('chief_flight_instructor', 'Chief Flight Instructor'), ('flight_instructor', 'Flight Instructor'), ('system_admin', 'System Admin'), ('admin_responsible', 'Admin Responsible'), ('admin_agent', 'Admin Agent'), ('finance_responsible', 'Finance Responsible'), ('accounting_agent', 'Accounting Agent'), ('admissions_responsible', 'Admissions Responsible'), ('quality_manager', 'Quality Manager'), ('compliance_monitoring_manager', 'Compliance Monitoring Manager'), ('safety_manager', 'Safety Manager'), ('scheduler', 'Scheduler'), ('training_admin', 'Training Administrator'), ('student', 'Student'), ('candidate', 'Candidate'), ('graduate', 'Graduate')], default='student', max_length=50),
        ),
    ]
