# Generated by Django 5.1.15 on 2026-07-11 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_profiles',
            },
        ),
        migrations.CreateModel(
            name='FlightInstructor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('qualifications', models.JSONField(blank=True, default=list)),
                ('authorized_aircraft_types', models.JSONField(blank=True, default=list)),
                ('total_flight_hours', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('instruction_hours', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('status', models.CharField(default='active', max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('medical_expiry', models.DateField(blank=True, null=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flight_instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flight Instructor',
                'verbose_name_plural': 'Flight Instructors',
                'db_table': 'flight_instructors',
            },
        ),
        migrations.CreateModel(
            name='GroundInstructor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('qualifications', models.JSONField(blank=True, default=list)),
                ('authorized_subjects', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='active', max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('medical_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ground_instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ground Instructor',
                'verbose_name_plural': 'Ground Instructors',
                'db_table': 'ground_instructors',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('enrollment_date', models.DateField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('program', models.CharField(choices=[('PPL', 'Private Pilot License'), ('CPL', 'Commercial Pilot License'), ('IR', 'Instrument Rating'), ('MEP', 'Multi-Engine Piston'), ('MCC', 'Multi-Crew Cooperation')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicyear')),
                ('main_instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='students.student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('issuer', models.CharField(blank=True, max_length=255, null=True)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='valid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_certificates', to='students.student')),
            ],
            options={
                'verbose_name': 'Medical Certificate',
                'verbose_name_plural': 'Medical Certificates',
                'db_table': 'medical_certificates',
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_number'], name='students_student_fa2474_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['program'], name='students_program_c510a3_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='students_status_3ac771_idx'),
        ),
    ]
