# Generated by Django 6.0.7 on 2026-08-01 23:22

import django.db.models.deletion
import uuid
import datetime
from django.db import migrations, models


def backfill_promotions(apps, schema_editor):
    AcademicYear = apps.get_model('core', 'AcademicYear')
    Promotion = apps.get_model('students', 'Promotion')
    Student = apps.get_model('students', 'Student')

    from collections import OrderedDict
    groups = OrderedDict()
    for s in Student.objects.all().order_by('enrollment_date', 'student_number'):
        key = (s.academic_year_id, s.program)
        groups.setdefault(key, []).append(s)

    promo_by_key = {}
    for (ay_id, program), students in groups.items():
        ay = None
        if ay_id:
            ay = AcademicYear.objects.filter(id=ay_id).first()
        year = ay.start_date.year if ay else 2025
        base = f'{program}-{year}-'
        letter_index = Promotion.objects.filter(code__startswith=base).count()
        letter = chr(ord('A') + letter_index)
        code = f'{base}{letter}'
        promo = Promotion.objects.create(
            code=code,
            program=program,
            name=f'{program} {year} {letter}',
            start_date=ay.start_date if ay else datetime.date(year, 9, 1),
            end_date=None,
            status='in_progress',
        )
        promo_by_key[(ay_id, program)] = promo

    for (ay_id, program), students in groups.items():
        promo = promo_by_key[(ay_id, program)]
        seq = 0
        for s in students:
            seq += 1
            s.promotion_id = promo.id
            s.student_number = f'STU-{promo.code}-{seq:03d}'
            s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('program', models.CharField(choices=[('PPL', 'Private Pilot License'), ('CPL', 'Commercial Pilot License'), ('IR', 'Instrument Rating'), ('MEP', 'Multi-Engine Piston'), ('MCC', 'Multi-Crew Cooperation')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('graduated', 'Graduated'), ('archived', 'Archived')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='students.flightinstructor')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'db_table': 'promotions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.promotion'),
        ),
        migrations.RunPython(backfill_promotions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='student',
            name='academic_year',
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['program'], name='promotions_program_999e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['status'], name='promotions_status_239aab_idx'),
        ),
    ]
