# Generated by Django 5.1.15 on 2026-08-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_academic_year_promotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
